layout_spectrum: 0.2939068
color:
  saturation: 0.3225806
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#040403'
  rhythmicContrast: 0.06272402
typography_spectrum: 0.4229391
name: Egeisler
